version: '3.8'

services:
  practice_app:
    image: peterj0412/practice:latest
    ports:
      - "5000:5000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      #Standard HTTPS port
      - "443:443"
      #Standard HTTP port
      - "80:80"

        #The localhost ports mapping, changed to linux server setup.
#      #Maps the website 8080 to port 80 in nginx.
#      - "8080:443"
#      #Map 8443 the https port to nginx port 443.
#      - "8443:443"
#      - "5001:80"

    #Locate nginx.conf and read volume I defined.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #Finds or creates a log folder for nginx on my laptop.
      - ./logs/nginx:/var/log/nginx
      #Give nginx access to certs folder.
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - practice_app
    restart: always