#Play 2, deploy application.
- name: Deploy Application
  hosts: web_servers
  gather_facts: true
  vars:
    #Change the root from my local machine to ubuntu dir.
    project_root: "/home/ubuntu/practice/"


  tasks:

    - name: Ensure project directory exists
      become: true
      file:
        path: "{{ project_root }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    #Copy files to server, will replace this with github auto deploy later.
#    - name: Copy project files to server
#      copy:
#        src: "{{ item }}"
#        dest: "{{ project_root }}"
#        mode: '0755'
#      loop:
#        - "../app.py"
#        - "../Dockerfile"
#        - "../docker-compose.yml"
#        - "../nginx.conf"
#        - "../requirements.txt"
#        - "../templates"

    - name: Copy orchestration files to server
      copy:
        src: "{{ item }}"
        dest: "{{ project_root }}"
        mode: '0644'
      loop:
          - "../docker-compose.yml"
          - "../nginx.conf"

    - name: Ensure certs directory exists
      file:
        path: "{{ project_root }}/certs"
        state: directory
        mode: '0755'

    - name: Generate Nginx SSL Certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout {{ project_root }}/certs/nginx.key
        -out {{ project_root }}/certs/nginx.crt
        -subj "/C=US/ST=CA/L=Sacramento/O=Dev/CN=localhost"
      args:
        #Skips this task if the file already exists
        creates: "{{ project_root }}/certs/nginx.crt"

    - name: Set permissions
      become: true
      file:
        path: "{{ item }}"
        mode: '0644'
        #Modern fact naming for the current user
        owner: "{{ ansible_facts['user_id'] }}"
      loop:
        - "{{ project_root }}/certs/nginx.key"
        - "{{ project_root }}/certs/nginx.crt"

    - name: Pull and Restart
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/practice
        state: present
        pull: always
