[manager]
localhost ansible_connection=local

#Hardcode this part for now, change later when I work with AWS.
[workers]
mac_mini ansible_host=peter-mini.local ansible_user=peter
#mac_mini ansible_connection=local