name: Auto Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch: #Manually click run in github.

jobs:
  terraform-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v4

      #Install terraform on github runner.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #The tfvars file has been logged in repo secrets, make it into a file again.
      - name: Create tfvars file
        working-directory: ./terraform/dev
        run: |
          echo "${{ secrets.TFVARS_CONTENT }}" > terraform.tfvars
          cat terraform.tfvars

      #Same with AWS access keys.
      - name: Terraform Init & Apply
        working-directory: ./terraform/dev
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible Dependencies
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      #Create .pem key from repo secret.
      - name: Setup SSH Key
        run: |
          mkdir -p keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keys/practice.pem
          chmod 400 keys/practice.pem

      - name: Run Ansible Playbook
        run: ansible-playbook -i terraform/dev/inventory.ini ansible/site.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
